export const ICONS = {
  iconHomeActive: require('assets/icons/iconHomeActive.png'),
  iconHomeInactive: require('assets/icons/iconHomeInactive.png'),
  icChveronLeftWhite100: require('assets/icons/icChveronLeftWhite100.png'),
  iconChevronLeftBold: require('assets/icons/iconChevronLeftBold.png'),
  iconChevronLeftGray: require('assets/icons/iconChevronLeftGray.png'),
  iconChevronLeftBlack: require('assets/icons/iconChevronLeftBlack.png'),
  icChveronRightGray600: require('assets/icons/icChveronRightGray600.png'),
  iconChevronRightBlack: require('assets/icons/iconChevronRightBlack.png'),
  iconChevronRightGray: require('assets/icons/iconChevronRightGray.png'),
  iconBell: require('assets/icons/iconBell.png'),
  iconMapMarker: require('assets/icons/mapMarker.png'),
  blankProfile: require('assets/icons/blankProfile.png'),
  iconSearch: require('assets/icons/search.png'),
  iosBack: require('assets/icons/iosBack.png'),
  x: require('assets/icons/x.png'),
};
