export const IMAGES = {
  bwLogo1: require('assets/images/bwLogo_1.png'),
  bwLogo2: require('assets/images/bwLogo_2.png'),
  bwWord: require('assets/images/bwWord.png'),
  event: require('assets/images/event.png'),
  announcement: require('assets/images/announcement.png'),
  following: require('assets/images/following.png'),
  my: require('assets/images/my.png'),
  finished: require('assets/images/finished.png'),
  selected: require('assets/images/selected.png'),
  received: require('assets/images/received.png'),
  applied: require('assets/images/applied.png'),
  placeholder: require('assets/images/placeholder.png'),
  betterWorldPlanet: require('assets/images/betterWorldPlanet.png'),
};
