export const NAV_NAMES = {
    SignIn: 'SignIn',
    SignUp: 'SignUp',
    Onboarding: 'Onboarding',
    Home: 'Home',
    Search: 'Search',
    Mood: 'Mood',
    Villain: 'Villain',
    Profile: 'Profile',
    OtherProfile: 'OtherProfile',
    NftCollection: 'NftCollection',
    Splash: "Splash",
    Post: "Post",
    NewPost: "NewPost",
    Report: "Report",
    Select: "Select",
    Capsule: "Capsule",
    Chat: "Chat",
    ChatRoom: "ChatRoom",
    PostDetail: "PostDetail",
    Notification: "Notification",
};

