require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'sungan' do
  config = use_native_modules!

  rn_maps_path = '../node_modules/react-native-maps'

  pod 'YogaKit'
  pod 'react-native-google-maps', path: rn_maps_path # enable google maps in ios environment
  pod 'GoogleMaps' # enable google maps in ios environment
  pod 'Google-Maps-iOS-Utils' # enable google maps in ios environment

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )

  target 'sunganTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  use_flipper!()

  pre_install do |installer|
    $RNMBGL.pre_install(installer)
  end

  post_install do |installer|
    $RNMBGL.post_install(installer)
    react_native_post_install(installer)
  end
end